SELECT A.CATEGORY,A.MAX_PRICE,B.PRODUCT_NAME
  FROM (SELECT CATEGORY,MAX(PRICE) AS MAX_PRICE
          FROM FOOD_PRODUCT
      GROUP BY CATEGORY
        HAVING CATEGORY IN ('과자','국','김치','식용유')
       ) A, FOOD_PRODUCT B
 WHERE A.CATEGORY = B.CATEGORY
   AND A.MAX_PRICE = B.PRICE
ORDER BY A.MAX_PRICE DESC