
                                     
SELECT
    P.PRODUCT_ID, P.PRODUCT_NAME,
    SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER O
    LEFT JOIN FOOD_PRODUCT P
    ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE, 'YYYYMM') = '202205'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY 3 DESC, 1 ASC;