SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ('Lucy','Ella','Pickle','Rogan','Sabrina','Mitty')
ORDER BY ANIMAL_ID ASC

-- SELECT A.ANIMAL_ID, A.NAME, A.SEX_UPON_INTAKE
-- FROM ANIMAL_INS A
-- WHERE A.NAME IN (
-- 'Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty')
-- ORDER BY A.ANIMAL_ID